"""empty message

Revision ID: a2ab9634354a
Revises: 2e89341f7d23
Create Date: 2020-07-04 14:30:05.790391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ab9634354a'
down_revision = '2e89341f7d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_car', sa.Column('car_id', sa.Integer(), nullable=False))
    op.drop_column('user_car', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_car', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user_car', 'car_id')
    # ### end Alembic commands ###
